# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(450, 600)
        MainWindow.setMinimumSize(QtCore.QSize(450, 600))
        MainWindow.setMaximumSize(QtCore.QSize(450, 600))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.nameInput = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.nameInput.setEnabled(False)
        self.nameInput.setGeometry(QtCore.QRect(110, 60, 113, 21))
        self.nameInput.setObjectName("nameInput")
        self.typeCombo = QtWidgets.QComboBox(parent=self.centralwidget)
        self.typeCombo.setEnabled(False)
        self.typeCombo.setGeometry(QtCore.QRect(110, 170, 111, 22))
        self.typeCombo.setObjectName("typeCombo")
        self.typeCombo.addItem("")
        self.typeCombo.addItem("")
        self.NamountInput = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.NamountInput.setEnabled(False)
        self.NamountInput.setGeometry(QtCore.QRect(110, 140, 113, 21))
        self.NamountInput.setObjectName("NamountInput")
        self.createBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.createBtn.setEnabled(False)
        self.createBtn.setGeometry(QtCore.QRect(110, 200, 111, 24))
        self.createBtn.setObjectName("createBtn")
        self.depositBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.depositBtn.setEnabled(False)
        self.depositBtn.setGeometry(QtCore.QRect(250, 280, 91, 24))
        self.depositBtn.setObjectName("depositBtn")
        self.withdrawBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.withdrawBtn.setEnabled(False)
        self.withdrawBtn.setGeometry(QtCore.QRect(250, 310, 91, 24))
        self.withdrawBtn.setObjectName("withdrawBtn")
        self.outputBox = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.outputBox.setGeometry(QtCore.QRect(120, 380, 211, 131))
        self.outputBox.setObjectName("outputBox")
        self.accountCombo = QtWidgets.QComboBox(parent=self.centralwidget)
        self.accountCombo.setEnabled(False)
        self.accountCombo.setGeometry(QtCore.QRect(250, 60, 68, 22))
        self.accountCombo.setObjectName("accountCombo")
        self.accountCombo.addItem("")
        self.accountCombo.setItemText(0, "")
        self.createRbn = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.createRbn.setGeometry(QtCore.QRect(110, 30, 111, 20))
        self.createRbn.setObjectName("createRbn")
        self.existingBtn = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.existingBtn.setGeometry(QtCore.QRect(240, 30, 111, 20))
        self.existingBtn.setObjectName("existingBtn")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(190, 0, 71, 20))
        self.label.setObjectName("label")
        self.balanceViewer = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.balanceViewer.setEnabled(False)
        self.balanceViewer.setGeometry(QtCore.QRect(250, 170, 191, 81))
        self.balanceViewer.setObjectName("balanceViewer")
        self.EamountInput = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.EamountInput.setEnabled(False)
        self.EamountInput.setGeometry(QtCore.QRect(250, 140, 113, 21))
        self.EamountInput.setObjectName("EamountInput")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setEnabled(False)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 81, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setEnabled(False)
        self.label_3.setGeometry(QtCore.QRect(30, 140, 49, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setEnabled(False)
        self.label_4.setGeometry(QtCore.QRect(20, 170, 81, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setEnabled(False)
        self.label_5.setGeometry(QtCore.QRect(340, 60, 71, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setEnabled(False)
        self.label_6.setGeometry(QtCore.QRect(380, 140, 49, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(200, 340, 49, 16))
        self.label_7.setObjectName("label_7")
        self.pinEnter = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.pinEnter.setEnabled(False)
        self.pinEnter.setGeometry(QtCore.QRect(250, 100, 71, 21))
        self.pinEnter.setObjectName("pinEnter")
        self.pinCreate = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.pinCreate.setEnabled(False)
        self.pinCreate.setGeometry(QtCore.QRect(110, 100, 113, 21))
        self.pinCreate.setObjectName("pinCreate")
        self.pinLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.pinLabel.setEnabled(False)
        self.pinLabel.setGeometry(QtCore.QRect(10, 90, 101, 31))
        self.pinLabel.setObjectName("pinLabel")
        self.pinLabel2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.pinLabel2.setEnabled(False)
        self.pinLabel2.setGeometry(QtCore.QRect(340, 100, 81, 16))
        self.pinLabel2.setObjectName("pinLabel2")
        self.showBalanceBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.showBalanceBtn.setEnabled(False)
        self.showBalanceBtn.setGeometry(QtCore.QRect(250, 250, 91, 24))
        self.showBalanceBtn.setObjectName("showBalanceBtn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 450, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.existingBtn.toggled['bool'].connect(self.accountCombo.setEnabled) # type: ignore
        self.createRbn.toggled['bool'].connect(self.nameInput.setEnabled) # type: ignore
        self.createRbn.toggled['bool'].connect(self.NamountInput.setEnabled) # type: ignore
        self.createRbn.toggled['bool'].connect(self.typeCombo.setEnabled) # type: ignore
        self.createRbn.toggled['bool'].connect(self.createBtn.setEnabled) # type: ignore
        self.existingBtn.toggled['bool'].connect(self.EamountInput.setEnabled) # type: ignore
        self.existingBtn.toggled['bool'].connect(self.balanceViewer.setEnabled) # type: ignore
        self.existingBtn.toggled['bool'].connect(self.depositBtn.setEnabled) # type: ignore
        self.existingBtn.toggled['bool'].connect(self.withdrawBtn.setEnabled) # type: ignore
        self.existingBtn.toggled['bool'].connect(self.label_5.setEnabled) # type: ignore
        self.existingBtn.toggled['bool'].connect(self.label_6.setEnabled) # type: ignore
        self.createRbn.toggled['bool'].connect(self.label_4.setEnabled) # type: ignore
        self.createRbn.toggled['bool'].connect(self.label_3.setEnabled) # type: ignore
        self.createRbn.toggled['bool'].connect(self.label_2.setEnabled) # type: ignore
        self.createRbn.toggled['bool'].connect(self.pinCreate.setEnabled) # type: ignore
        self.createRbn.toggled['bool'].connect(self.pinLabel.setEnabled) # type: ignore
        self.existingBtn.toggled['bool'].connect(self.pinEnter.setEnabled) # type: ignore
        self.existingBtn.toggled['bool'].connect(self.pinLabel2.setEnabled) # type: ignore
        self.existingBtn.toggled['bool'].connect(self.showBalanceBtn.setEnabled) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.typeCombo.setItemText(0, _translate("MainWindow", "Account"))
        self.typeCombo.setItemText(1, _translate("MainWindow", "Saving Account"))
        self.createBtn.setText(_translate("MainWindow", "Create Account"))
        self.depositBtn.setText(_translate("MainWindow", "Deposit"))
        self.withdrawBtn.setText(_translate("MainWindow", "Withdraw"))
        self.createRbn.setText(_translate("MainWindow", "Create Account"))
        self.existingBtn.setText(_translate("MainWindow", "Existing Account"))
        self.label.setText(_translate("MainWindow", "Bank of UNO"))
        self.label_2.setText(_translate("MainWindow", "Account Name"))
        self.label_3.setText(_translate("MainWindow", "Amount"))
        self.label_4.setText(_translate("MainWindow", "Account Type"))
        self.label_5.setText(_translate("MainWindow", "Accont Name"))
        self.label_6.setText(_translate("MainWindow", "Amount"))
        self.label_7.setText(_translate("MainWindow", "Output"))
        self.pinLabel.setText(_translate("MainWindow", "Create 4 Digit Pin"))
        self.pinLabel2.setText(_translate("MainWindow", "4-Digit Pin"))
        self.showBalanceBtn.setText(_translate("MainWindow", "Show Balance"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
